### ISSUE TITLE
Launcher show warning on Java version

### ISSUE THREAD

**Issue by Maypul** [MCTeamPotato/ForceJava21#2]
MC: 1.19.2
Forge: 43.3.7

Hello there!
I wanted to try this mod and unfortunately it seems I am not able to run my MC at all.
I am using PRISM launcher and tested with few different Java 21, but the one I wanted to run with was Adoptium 21.

When I launch my game, I get:
This instance is not compatible with Java version 21.
Please switch to one of the following Java versions for this instance:
Java version 17
Go to instance Java settings to change your Java version or disable the Java compatibility check if you know what you're doing.

(I point to Java 21 in the launcher seettings, and tests passes, Java 21 is detected just fine). When I switch back to Java 17 I get the following:
Please use Java 21+ to launch Minecraft
Current Java version: 17.
Recommendations: 
Zulu: https://www.azul.com/downloads/?version=java-21-lts&package=jdk#zulu
Oracle: https://www.oracle.com/java/technologies/downloads/#java21
Temurin: https://adoptium.net/temurin/releases/?version=21
Process exited with code -1.

Current client mod list (which I assume something must be conflicting): https://pastebin.com/AQVHGEEi

**Comment by Kasualix** [comment]
The launcher warning is understandable but not resolvable in the mod's end, you do can mute Java version detection and let it go in prism settings.

**Comment by Maypul** [comment]
Blind as usual, I though I tested with this setting on. Thanks for pointing it out.
